[package]
name = "json2pb"
version = "0.2.1"
authors = ["ronaldoliu@tencent.com"]
description = "convert json object to protobuf message"
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/caibirdme/json2pb"
readme = "README.md"
keywords = ["json", "protobuf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "json2pb"
path = "src/lib.rs"

[[bin]]
name = "j2pb"
path = "src/bin/j2pb.rs"

[dependencies]
clap = "2.34.0"
nom = "6.2.2"
